# Module name: enums/event.py
# Author: (wattleflow@outlook.com)
# Copyright: © 2022–2026 WattleFlow. All rights reserved.
# License: Apache 2 Licence


# --------------------------------------------------------------------------- #
# region Imports                                                              #
# --------------------------------------------------------------------------- #
from __future__ import annotations
from enum import StrEnum
# --------------------------------------------------------------------------- #
# endregion Imports                                                           #
# --------------------------------------------------------------------------- #

# --------------------------------------------------------------------------- #
# region Enums                                                                #
# --------------------------------------------------------------------------- #


# Events
# v0.0.1.14 (DR-WFL-032): a member IS its name — `msg=Event.Write` costs 57 ns where
# `Event.Write` cost 144 ns (an `enum.property` per access, twice per record).
# Every value equals its name so `.name`, `.value` and the member read the same.
class Event(StrEnum):
    Idle = "Idle"
    Accessing = "Accessing"
    Added = "Added"
    Adding = "Adding"
    Audit = "Audit"
    Authenticate = "Authenticate"
    Authentication = "Authentication"
    Authenticating = "Authenticating"
    Authenticated = "Authenticated"
    Build = "Build"
    Cache = "Cache"
    Cached = "Cached"
    Caching = "Caching"
    Check = "Check"
    Checking = "Checking"
    Classification = "Classification"
    Classified = "Classified"
    Classifying = "Classifying"
    Clean = "Clean"
    Cleaned = "Cleaned"
    Cleaning = "Cleaning"
    Clear = "Clear"
    Cleared = "Cleared"
    Clearing = "Clearing"
    Close = "Close"
    Closed = "Closed"
    Closing = "Closing"
    Completed = "Completed"
    Completing = "Completing"
    Constructor = "Constructor"
    Connect = "Connect"
    Connected = "Connected"
    Connecting = "Connecting"
    Connection = "Connection"
    Configure = "Configure"
    Configured = "Configured"
    Configuring = "Configuring"
    Configuration = "Configuration"
    Context = "Context"
    Copy = "Copy"
    Copying = "Copying"
    Copied = "Copied"
    Create = "Create"
    Creating = "Creating"
    Created = "Created"
    CriticalError = "CriticalError"
    CronJobSchedulerError = "CronJobSchedulerError"
    DebugLog = "DebugLog"
    Debug = "Debug"
    Debugging = "Debugging"
    Delete = "Delete"
    Deleted = "Deleted"
    Deleting = "Deleting"
    Destruct = "Destruct"
    Destructed = "Destructed"
    Destructing = "Destructing"
    Destructor = "Destructor"
    Detect = "Detect"
    Detected = "Detected"
    Detecting = "Detecting"
    Disconnect = "Disconnect"
    Disconnecting = "Disconnecting"
    Disconnected = "Disconnected"
    Download = "Download"
    Downloading = "Downloading"
    Downloaded = "Downloaded"
    Enter = "Enter"
    Entered = "Entered"
    Entering = "Entering"
    Emit = "Emit"
    Emitted = "Emitted"
    Emitting = "Emitting"
    Exist = "Exist"
    Exists = "Exists"
    Existing = "Existing"
    Exporting = "Exporting"
    Exported = "Exported"
    Execute = "Execute"
    Executed = "Executed"
    Executing = "Executing"
    Exit = "Exit"
    Exited = "Exited"
    Exiting = "Exiting"
    Error = "Error"
    ErrorSource = "ErrorSource"
    Extract = "Extract"
    Extracted = "Extracted"
    Extracting = "Extracting"
    ErrorDetails = "ErrorDetails"
    Failed = "Failed"
    Finish = "Finish"
    Finished = "Finished"
    Finishing = "Finishing"
    Find = "Find"
    Finding = "Finding"
    Found = "Found"
    Flush = "Flush"
    Flushing = "Flushing"
    Flushed = "Flushed"
    Generate = "Generate"
    Generating = "Generating"
    Generated = "Generated"
    Get = "Get"
    Getting = "Getting"
    Handle = "Handle"
    Handling = "Handling"
    Handled = "Handled"
    Initialising = "Initialising"
    Initialised = "Initialised"
    Iterate = "Iterate"
    Iterating = "Iterating"
    Iteration = "Iteration"
    List = "List"
    Listed = "Listed"
    Listing = "Listing"
    Load = "Load"
    Loaded = "Loaded"
    Loading = "Loading"
    Log = "Log"
    Miss = "Miss"
    Missed = "Missed"
    Missing = "Missing"
    Move = "Move"
    Moved = "Moved"
    Moving = "Moving"
    Notify = "Notify"
    Operate = "Operate"
    Operated = "Operated"
    Operation = "Operation"
    Operating = "Operating"
    OrchestrationCompleted = "OrchestrationCompleted"
    OrchestrationStarted = "OrchestrationStarted"
    OrchestrationStopped = "OrchestrationStopped"
    PipelineProcess = "PipelineProcess"
    Probe = "Probe"
    Probing = "Probing"
    Probed = "Probed"
    Process = "Process"
    Processed = "Processed"
    Processing = "Processing"
    ProcessingTask = "ProcessingTask"
    Property = "Property"
    Push = "Push"
    Pushed = "Pushed"
    Pushing = "Pushing"
    Read = "Read"
    Reading = "Reading"
    Register = "Register"
    Registered = "Registered"
    Registering = "Registering"
    Render = "Render"
    Rendered = "Rendered"
    Rendering = "Rendering"
    Resolve = "Resolve"
    Restore = "Restore"
    Retrieve = "Retrieve"
    Retrieved = "Retrieved"
    Retrieving = "Retrieving"
    Save = "Save"
    Search = "Search"
    Searched = "Searched"
    Searching = "Searching"
    Sleep = "Sleep"
    Sleeping = "Sleeping"
    Start = "Start"
    Started = "Started"
    Starting = "Starting"
    Store = "Store"
    Stored = "Stored"
    Storing = "Storing"
    Stop = "Stop"
    Stopped = "Stopped"
    Stopping = "Stopping"
    Subscribe = "Subscribe"
    Subscribed = "Subscribed"
    Subscribing = "Subscribing"
    Swap = "Swap"
    Test = "Test"
    Testing = "Testing"
    Tested = "Tested"
    Transform = "Transform"
    Transformed = "Transformed"
    Transforming = "Transforming"
    TaskCompleted = "TaskCompleted"
    Unregister = "Unregister"
    Unregistering = "Unregistering"
    Unregistered = "Unregistered"
    Update = "Update"
    Updated = "Updated"
    Updating = "Updating"
    Upload = "Upload"
    Uploading = "Uploading"
    Uploaded = "Uploaded"
    Validate = "Validate"
    Validated = "Validated"
    Validating = "Validating"
    View = "View"
    Viewed = "Viewed"
    Viewing = "Viewing"
    Write = "Write"
    Writing = "Writing"
    Written = "Written"


# --------------------------------------------------------------------------- #
# endregion Enums                                                             #
# --------------------------------------------------------------------------- #

__all__ = [
    "Event",
]
