from setuptools import setup, find_packages

setup(
    name="wattleflow",
    description="WattleFlow Workflow",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="WattleFlow",
    author_email="wattleflow@outlook.com",
    url="https://github.com/wattleflow/workflow.git",
    license="Apache-2.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    include_package_data=True,
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "License :: OSI Approved :: Apache Software License",
    ],
    python_requires=">=3.9",
    setup_requires=["setuptools_scm"],
    use_scm_version=True,
    install_requires=[
        "pyyaml",
        "cryptography",
        "wattleflow>=0.0.0.7",
        "pytesseract>=0.3.10",
        "rdflib>=7.1.2",
        "tika>=2.6.0",
        "youtube-transcript-api>=0.6.3",
    ],
    extras_require={},
)
