@startuml

title GenericBlackboard - persistance layer
caption ...built once use often...
top to bottom direction

frame " " {
    class GenericBlackboard {
      + create(*args, **kwargs): DocumentFacade
      + write(document: DocumentFacade) : uuid
      + repositories: List
    }

    class CreateStrategy {
      + create: DocumentFacade
    }

    class GenericRepository {
      + write(document: DocumentFacade) : uuid
    }

    class WriteStrategy {
      + write() : uuid
    }

    class DocumentFacade {
      + update_cotntent()
    }    
}

GenericBlackboard "1" --> "1" CreateStrategy: creates
GenericBlackboard "1" --> "many" GenericRepository: write
GenericRepository "many" --> "many" WriteStrategy: write
CreateStrategy "1" o--> "1" DocumentFacade: creates

note "@copyright Wattleflow" as N1 #Yellow
@enduml
