@startuml
title Workflow - Data persistance diagram
caption ...built once use often...

skinparam linetype ortho
!pragma teoz true

package wattleflow.workflow {
  frame persistance {
    note "@copyright Wattleflow" as N1
    class GenericBlackboard {
      + canvas(): Mapping[str, ITarget]
      + count(): int
      + repositories(): Mapping[str, IRepository]
      + clear()
      + create(caller, *args, **kwargs): Optional[ITarget]
      + delete(caller, identifier: str): None
      + flush(caller, *args, **kwargs): None
      + read(identifier: str): ITarget
      + read_from(repository_name, identifier, *args, **kwargs): ITarget
      + register(repository: IRepository): None
      + write(caller, document, *args, **kwargs): str
    }

    class GenericRepository {
      + count(): int
      + clear(): None
      + read(identifier: str, *args, **kwargs): ITarget
      + write(caller: document, *args, **kwargs): bool
    }

    class CreateStrategy {
      + execute()
    }

    class ReadStrategy {
      + execute()
    }

    class WriteStrategy {
      + execute()
    }

    class DocumentFacade {
      + update_content()
    }

  }
}

GenericBlackboard "1" o--|> "1" CreateStrategy: create
CreateStrategy o--|> DocumentFacade
GenericBlackboard "1" o--|> "1" GenericRepository: "read"
GenericBlackboard "1" o--|> "1" GenericRepository: "write"
GenericRepository "1" o--|> "1" ReadStrategy: read
GenericRepository "1" o--|> "1" WriteStrategy: write

@enduml
