@startuml

title GenericBlackboard - class diagram
caption ...ensures audit and streamline data via persistance layer...

skinparam linetype ortho
!pragma teoz true

top to bottom direction
' left to right direction

frame wattleflow {
  class IBlackboard
}

frame workflow {
  class AuditLogger
  class GenericBlackboard {
    + canvas(): Mapping[str, ITarget]
    + count(): int
    + repositories(): Mapping[str, IRepository]
    + clear()
    + create(caller, *args, **kwargs): Optional[ITarget]
    + delete(caller, identifier: str): None
    + flush(caller, *args, **kwargs): None
    + read(identifier: str): ITarget
    + read_from(repository_name,identifier,*args,**kwargs): ITarget
    + register(repository): None
    + write(caller, document, *args, **kwargs): str
  }
  note "@copyright Wattleflow" as N1 #Yellow

  class GenericRepository {
    +read()
    +write()
  }
  class CreateStrategy {
    +execute()
  }
  class DocumentFacade
}

IBlackboard <|-- GenericBlackboard: inherits
AuditLogger <|-- GenericBlackboard: inherits
GenericBlackboard "1" --> "1" CreateStrategy: create
GenericBlackboard "0" --> "1" GenericRepository: read_from
GenericBlackboard "0" --> "many" GenericRepository: write
DocumentFacade --> CreateStrategy : creates

@enduml
