@startuml

title GenericConnection - class diagram
caption ...ensures audit and provides facade for all connections...

skinparam linetype ortho
!pragma teoz true

frame "workflow" {
  class ConnectionObserverInterface {
    + subscribe(observer): None
    + subscribe_observer(observer): None
    + notify(owner, **kwargs)
    + operation(action: Operation): bool
  }
  class GenericConnection {
    + connected(): bool
    + connection(): object
    + operation(action: Operation): bool
    + context()
    + create_connection(**configuration)
    + connect(): bool
    + disconnect(): bool
  }
}
IObservable <|-- ConnectionObserverInterface
IFacade <|-- ConnectionObserverInterface
ConnectionObserverInterface <|-- GenericConnection
AuditLogger <|-- GenericConnection
@enduml
