@startuml

title Orchestrator - class diagram
caption \n...facade that orchestrates data pipelines work...

skinparam linetype ortho
!pragma teoz true
' top to bottom direction
' left to right direction

frame wattleflow {
  class IEventSource
  class IFacade
}
frame "workflow" {
  class Orchestrator {
    + add_processor(processor: IProcessor)
    + emit_event(event: Event, **kwargs)
    + register_listener(listener: IEventListener): None
    + operation(action: Operation)
    + start(parallel: bool)
    + stop()
  }

    class GenericProcessor {
      + start()
    }

    together {
      frame List {
        class GenericPipeline {
          + process()
        }
      }
      note "@copyright Wattleflow" as N1
  }
}

IEventSource <|-- Orchestrator: "inherits"
IFacade <|-- Orchestrator: "inherits"
Orchestrator "0" <--o "many" GenericProcessor: add
GenericProcessor "0" o--> "many" GenericPipeline: process

@enduml
