# Module name: enum.py
# Author: (wattleflow@outlook.com)
# Copyright: © 2022–2025 WattleFlow. All rights reserved.
# License: Apache 2 Licence


from __future__ import annotations
from enum import Enum


# Classification
class Classification(Enum):
    CLASSIFIED = "Classified"
    OFFICIAL = "OFFICIAL"
    PROTECTED = "PROTECTED"
    SECRET = "SECRET"
    TOP_SECRET = "TOP SECRET"
    UNCLASSIFIED = "UNCLASSIFIED"


# Classification DLM
class ClassificationDLM(Enum):
    CABINET = "CABINET"
    LEGAL_PREVILEGE = "Legal Privilege"
    PERSONAL = "Personal"
    SENSITIVE = "Sensitive"
    UNCLASSIFIED = "UNCLASSIFIED"
    UNDEFINED = "Undefined"


# Events
class Event(Enum):
    Idle = "Idle"
    Accessing = "Accessing"
    Added = "Added"
    Adding = "Adding"
    Audit = "Audit"
    Authenticate = "Authenticate"
    Authentication = "Authentication"
    Authenticating = "Authenticating"
    Authenticated = "Authenticated"
    Check = "Check"
    Checking = "Checking"
    Classification = "Classification"
    Classifyied = "Classified"
    Classifying = "Classifying"
    Clean = "Clean"
    Cleaned = "Cleaned"
    Cleaning = "Cleaning"
    Clear = "Clear"
    Cleared = "Cleared"
    Clearing = "Clearing"
    Completed = "Completed"
    Constructor = "Constructor"
    Connect = "Connect"
    Connected = "Connected"
    Connecting = "Connecting"
    Connection = "Connection"
    Configure = "Configure"
    Configured = "Configured"
    Configuring = "Configuring"
    Configuration = "Configuration"
    Context = "Context"
    Copy = "Copy"
    Copying = "Copying"
    Copied = "Copied"
    Create = "Create"
    Creating = "Creating"
    Created = "Created"
    CriticalError = "Critical error"
    CronJobSchedulerError = "CronJobSchedulerError"
    DebugLog = "Debug log"
    Debug = "Debug"
    Debuging = "Debuging"
    Delete = "Delete"
    Deleted = "Deleted"
    Deleting = "Deleting"
    Destruct = "Destruct"
    Destructed = "Destructed"
    Destructing = "Destructing"
    Destructor = "Destructor"
    Detect = "Detect"
    Detected = "Detected"
    Detecting = "Detecting"
    Disconnect = "Disconnect"
    Disconnecting = "Disconnecting"
    Disconnected = "Disconnected"
    Download = "Download"
    Downloading = "Downloading"
    Downloaded = "Downloaded"
    Enter = "Enter"
    Entered = "Entered"
    Entering = "Entering"
    Emit = "Emit"
    Emited = "Emited"
    Emiting = "Emiting"
    Exist = "Exist"
    Exists = "Exists"
    Existing = "Existing"
    Exporting = "Exporting"
    Exported = "Exported"
    Execute = "Execute"
    Executed = "Executed"
    Executing = "Executing"
    Exit = "Exit"
    Exited = "Exited"
    Exiting = "Exiting"
    Error = "Error"
    ErrorSource = "Error source"
    Exception = "Exception"
    Extract = "Extract"
    Extracted = "Extracted"
    Extracting = "Extracting"
    ErrorDetails = "Error details"
    Failed = "Failed"
    Finnish = "Finnish"
    Finnished = "Finnished"
    Finnishing = "Finnishing"
    Flush = "Flush"
    Flushing = "Flushing"
    Flushed = "Flushed"
    Generate = "Generate"
    Generating = "Generating"
    Generated = "Generated"
    Get = "Get"
    Getting = "Getting"
    Initialising = "Initialising"
    Initialised = "Initialised"
    Iterate = "Iterate"
    Iterating = "Iterating"
    Iteration = "Iteration"
    Log = "Log"
    Miss = "Miss"
    Missed = "Missed"
    Missing = "Missing"
    Move = "Move"
    Moved = "Moveed"
    Moving = "Moving"
    Operate = "Operate"
    Operated = "Operated"
    Operation = "Operation"
    Operating = "Operating"
    OrchestrationCompleted = "Orchestration completed"
    OrchestrationStarted = "Orchestration started"
    OrchestrationStopped = "Orchestration stopped"
    PipelineProces = "Pipeline process"
    Probe = "Probe"
    Probing = "Probing"
    Probed = "Probed"
    Process = "Process"
    Processed = "Processed"
    Processing = "Processing"
    ProcessingTask = "Processing task"
    Push = "Push"
    Pushed = "Pushed"
    Pushing = "Pushing"
    Read = "Read"
    Reading = "Reading"
    Register = "Register"
    Registered = "Registered"
    Registering = "Registering"
    Rendered = "Rendered"
    Rendering = "Rendering"
    Retrieve = "Retrieve"
    Retrieved = "Retrieved"
    Retrieving = "Retrieving"
    Search = "Search"
    Searched = "Searched"
    Searching = "Searching"
    Sleep = "Sleep"
    Sleeping = "Sleeping"
    Start = "Start"
    Started = "Started"
    Starting = "Starting"
    Store = "Store"
    Stored = "Stored"
    Storing = "Storing"
    Stop = "Stop"
    Stopped = "Stopped"
    Stopping = "Stopping"
    Subscribe = "Subscribe"
    Subscribed = "Subscribed"
    Subscribing = "Subscribing"
    Test = "Test"
    Testing = "Testing"
    Tested = "Tested"
    Transform = "Transform"
    Transformed = "Transformed"
    Transforming = "Transforming"
    TaskCompleted = "Task completed"
    Update = "Update"
    Updated = "Updated"
    Updating = "Updating"
    Upload = "Upload"
    Uploading = "Uploading"
    Uploaded = "Uploaded"
    View = "View"
    Viewed = "Viewed"
    Viewing = "Viewing"
    Write = "Write"
    Writing = "Writing"
    Writting = "Writting"
    Written = "Written"


class Operation(Enum):
    Start = 1
    Stop = 0
    Connect = 3
    Disconnect = 4


# Action
class PipelineAction(Enum):
    CONNECT = "5bb4dc6f-47d4-c040-9844-a72464984b14"
    DISCONNECT = "6ab06dcf-aa51-790d-d7c9-6d52d3be8ae0"
    EXTRACT = "40803834-9041-9ffc-e52d-9a66c5fac20b"
    TRANSFORM = "00c9bf50-c91c-2d07-e985-1cd554537678"
    LOAD = "d438686e-54df-812d-53df-373e2ca6a962"
    SCHEDULE = "5a40b6fd-b0ca-155a-3050-4aa62f93a7c5"
    RELEASE_DATE = "20241030"
    VERSION = "0.0.0.1"


# Supported pipline types
class PipelineType(Enum):
    ASYNC_PIPELINE = "ASYNC_PIPELINE"  # "2a6737f3-93f5-950b-832c-cfd78829c69c"
    BASE_PIPELINE = "BASE_PIPELINE"  # "1916fa2b-7d51-c4f2-e28e-61e8fc4c386d"
    CONFIGURATION_PIPELINE = "CONFIGURATION_PIPELINE"
    CONNECTION_PIPELINE = (
        "CONNECTION_PIPELINE"  # "c3535bf0-a399-8fce-a609-92c0b072fe52"
    )
    EXTRACTION_PIPELINE = (
        "EXTRACTION_PIPELINE"  # "df1999d3-28f7-a17d-764e-8d0eb9c01dca"
    )
    LOAD_PIPELINE = "LOAD_PIPELINE"  # "85593db0-62ba-e953-b9da-aa1860025880"
    # FEATURE_PIPELINE = "966fc1db-7e8c-62f2-178c-b3c74d8ba70b"
    STRATEGY_PIPELINE = "STRATEGY_PIPELINE"
    TRANSFORMATION_PIPELINE = (
        "TRANSFORMATION_PIPELINE"  # "fa7a9304-7b92-bf00-2374-a899ee239dfe"
    )
    RELEASE_DATE = "20241030"
    VERSION = "0.0.0.1"
